### ISSUE TITLE
Generated masterpassword is not stored encrypted

### ISSUE THREAD

**Issue by zkdev** [keycloud/keycloud#23]
https://github.com/keycloud/keycloud/blob/1719cc8849f68799b50da29e85c2fc6ea1b199bc/server/authnHandler.go#L185

After creation it should be encrypted and stored to database, not in plain text.

**Comment by Dudeldu** [comment]
Good idea, shouldn't be that much of a problem either. You would only have to hash the password on standard login the same way to compare them.

**Comment by zkdev** [comment]
Scheduled for next week.
